QLSV.Web/Areas/Gv/Controllers/DiemDanhController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using QLSV.Entities.Models;
using QLSV.Services.Services;

namespace QLSV.Web.Areas.Gv.Controllers
{
    public class DiemDanhController : Controller
    {
        private readonly DiemDanhService _diemDanhService;
        private readonly LopHocPhanSinhVienService _lopHocPhanSinhVienService;
        private readonly LopHocPhanService _lopHocPhanService;

        public DiemDanhController()
        {
            _diemDanhService = new DiemDanhService();
            _lopHocPhanSinhVienService = new LopHocPhanSinhVienService();
            _lopHocPhanService = new LopHocPhanService();
        }

        // GET: Gv/DiemDanh
        public ActionResult DanhSach(int id)
        {
            var giaoVien = new TaiKhoan();
            var requestCookie = Request.Cookies["GiaoVienInfo"];
            if (requestCookie != null)
            {
                var cookieString = HttpUtility.UrlDecode(requestCookie.Value);
                giaoVien = JsonConvert.DeserializeObject<TaiKhoan>(cookieString);
            }
            var lopHocPhan =
                _lopHocPhanService.Where(x => x.Id == id && x.GiaoVienId == giaoVien.IdNguoiDung).FirstOrDefault();
            if (lopHocPhan != null)
            {
                ViewBag.Menu = "Điểm danh lớp " + lopHocPhan.Ten;
                ViewBag.MenuIcon = "fa-user";
                return View();
            }
                return RedirectToAction("Index", "GvHome");
        }

        [HttpPost]
        public ActionResult TaoDanhSach(int id, DateTime ngayDiemDanh)
        {
            var date = ngayDiemDanh.Date;
            var dsDiemDanh = _diemDanhService.Where(x => x.LopHocPhanId == id && x.NgayDiemDanh == date).ToList();
            var giaoVien = new TaiKhoan();
            var requestCookie = Request.Cookies["GiaoVienInfo"];
            if (requestCookie != null)
            {
                var cookieString = HttpUtility.UrlDecode(requestCookie.Value);
                giaoVien = JsonConvert.DeserializeObject<TaiKhoan>(cookieString);
            }
            if (dsDiemDanh.Count > 0)
            {
                return Json("Exist", JsonRequestBehavior.AllowGet);
            }
            var listSv = _lopHocPhanSinhVienService.Where(x => x.LopHocPhanId == id);
            foreach (var sv in listSv)
            {
                var diemDanh = new DiemDanh
                {
                    SinhVienId = sv.SinhVienId,
                    CoMat = true,
                    Deleted = false,
                    GiaoVienId = giaoVien.IdNguoiDung.GetValueOrDefault(),
                    LopHocPhanId = id,
                    NgayDiemDanh = ngayDiemDanh,
                    Phep = false
                };
                _diemDanhService.Add(diemDanh);
            }
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
    }
}

QLSV.Web/Areas/Gv/Views/DiemDanh/DanhSach.cshtml
@using DevExtreme.AspNet.Mvc

@{
    ViewBag.Title = "Xem Điểm Danh";
    Layout = "/Areas/Gv/Views/Shared/_AdminLayout.cshtml";
}
<h1 style="text-align: center">Danh sách điểm danh ngày @DateTime.Now.ToString("d")</h1>
<div class="row">
    @(Html.DevExtreme().DataGrid()
          .ID("gridDanhSach")
          .Columns(columns =>
          {
              columns.Add()
                  .DataField("SinhVien.TenDayDu")
                  .Caption("Sinh Viên")
                  .AllowEditing(false);
              columns.Add()
                  .DataField("SinhVien.Lop.Ten")
                  .Caption("Lớp")
                  .AllowEditing(false);
              columns.Add()
                  .DataField("NgayDiemDanh")
                  .Caption("Ngày Điểm Danh")
                  .AllowEditing(false)
                  .CustomizeText("dateText")
                  .AllowFiltering(false);
              columns.Add()
                  .DataField("CoMat")
                  .Caption("Có mặt")
                  .DataType(GridColumnDataType.Boolean)
                  .AllowFiltering(false);
          })
          .HeaderFilter(headerFilter => headerFilter.Visible(true))
          .DataSource(d => d.WebApi().Controller("DiemDanhApi").LoadAction("Get")
              .LoadParams(new {id = new JS("returnId"), ngayDiemDanh = new JS("returnNgayDiemDanh")}).Key("Id"))
          .ShowBorders(true)
          .Editing(editing =>
          {
              editing.AllowUpdating(true);
              editing.Mode(GridEditMode.Batch);
              editing.Texts(t =>
              {
                  t.AddRow("Thêm mới");
                  t.EditRow("Sửa");
                  t.DeleteRow("Xóa");
                  t.CancelAllChanges("Hủy bỏ thay đổi");
                  t.CancelRowChanges("Hủy bỏ");
                  t.ConfirmDeleteMessage("Bạn có muốn xóa không?");
                  t.SaveAllChanges("Lưu thay đổi");
                  t.SaveRowChanges("Xác nhận");
              });
          })
          .ColumnAutoWidth(true)
          .ColumnChooser(c =>
          {
              c.Enabled(true);
              c.Title("Chọn cột hiển thị");
              c.EmptyPanelText("Kéo cột vào để ẩn đi");
          })
          )

</div>
<script>
    function getUrlVars() {
        var vars = {};
        var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,
            function(m, key, value) {
                vars[key] = value;
            });
        return vars;
    }

    returnId = function() {
        return getUrlVars()["id"];
    };

    var ngayDiemDanh = new Date().toISOString();

    function dateBox_valueChanged(data) {
        ngayDiemDanh = new Date(data.value).toISOString();
        var dataGrid = $("#gridDanhSach").dxDataGrid("instance");
        dataGrid.refresh();
    }

    returnNgayDiemDanh = function() {
        return ngayDiemDanh;
    }

    $.ajax({
        type: "POST",
        url: '@Url.Action("TaoDanhSach", "DiemDanh")',
        data: JSON.stringify({
            id: returnId(),
            ngayDiemDanh: returnNgayDiemDanh()
        }),
        dataType: "json",
        contentType: "application/json; charset=utf-8",
        success: function(res) {
            var dataGrid;
            if (res === "Exist") {
                dataGrid = $("#gridDanhSach").dxDataGrid("instance");
                dataGrid.refresh();
            } else {
                dataGrid = $("#gridDanhSach").dxDataGrid("instance");
                dataGrid.refresh();
            }
        },
        error: function() {
            alert('Error');
        }
    });

    $('#btnCreate').click(function() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("TaoDanhSach", "DiemDanh")',
            data: JSON.stringify({
                id: returnId(),
                ngayDiemDanh: returnNgayDiemDanh()
            }),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function(res) {
                if (res === "Exist") {
                    alert('Danh sách điểm danh đã tồn tại');
                } else {
                    var dataGrid = $("#gridDanhSach").dxDataGrid("instance");
                    dataGrid.refresh();
                }
            },
            error: function() {
                alert('Error');
            }
        });
        return false;
    });
</script>